services:
  - type: web
    name: whatsapp-gpt-bot
    runtime: python
    repo: https://github.com/your-username/whatsapp-gpt-bot
    pythonVersion: 3.11.8       # ✅ Force Python version (equivalent to runtime.txt)
    buildCommand: ""            # Optional: leave blank if no custom build needed
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HUBSPOT_API_KEY
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
